[project]
name = "qlibx"
version = "0.1.0"
description = "Qlib-native alpha research framework"
readme = "README.md"
authors = [
    { name = "Jaepil.Choi", email = "chljeffreyz@gmail.com" }
]
requires-python = ">=3.10,<3.13"
dependencies = []

[project.scripts]
qlibx = "qlibx:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"
