"""Public package surface for qlibx."""

from qlibx.analysis import (
    AnalysisResult,
    MonitoringAnalysisRequest,
    RendererKind,
    ReportRequest,
    ReportResult,
    SignalAnalysisRequest,
    SimulationAnalysisRequest,
)
from qlibx.contracts import (
    ArtifactSemanticConstraint,
    BudgetMode,
    DecisionAction,
    EveryCandidate,
    EveryNSessions,
    ForwardReturnLabelEntry,
    ForwardReturnLabelModel,
    ForwardReturnLabelResult,
    ModelInvocation,
    ModelOutputContract,
    ResearchModel,
    StoredSignalEntry,
    StoredSignalResult,
    StrategyArtifactBinding,
    StrategyArtifactRequirement,
    StrategyDraft,
    StrategyInvocation,
    StrategyResult,
    StrategySourceStateLineage,
    TriggerContext,
    TriggerDecision,
    TriggerPolicy,
    WeightEntry,
)
from qlibx.data import (
    AvailableAtField,
    CalendarLookback,
    ComponentRequirement,
    ConfirmedDelayRule,
    DatasetRegistration,
    DatasetReindexResult,
    RowsLookback,
    SourceFormat,
)
from qlibx.errors import OperationError, OperationOutcome, OutcomeStatus
from qlibx.execution import (
    AcademicExecutionPreparation,
    BaseExchange,
    CostRule,
    EtfInstrument,
    ExecutionPreparation,
    KrxBatchRequest,
    KrxExchange,
    KrxExchangeConfig,
    KrxExecutionPreparation,
    MatchBatchResult,
    Side,
    StockInstrument,
)
from qlibx.execution.academic import (
    AcademicBatchRequest,
    AcademicExchange,
    AcademicExchangeProfile,
    AcademicFill,
    AcademicInstrumentKind,
    AcademicInstrumentListing,
    AcademicMatchResult,
    AcademicPortfolioSnapshot,
    AcademicPortfolioState,
    AcademicPositionState,
    AcademicPriceSemantics,
    AcademicQuote,
    AcademicTargetWeight,
)
from qlibx.extensions import (
    RegisteredStrategyExtension,
    StrategyArtifactModelRegistration,
    StrategyArtifactModelSpec,
    StrategyExtensionRegistration,
    StrategyExtensionSpec,
    StrategyExtensionValidationRequest,
    StrategyExtensionValidationResult,
)
from qlibx.flow import (
    ACADEMIC_EXECUTION_CONTRACT,
    STORED_SIGNAL_CONTRACT,
    EnsembleDefinition,
    EnsembleMemberSpec,
    StoredSignalWeighting,
)
from qlibx.models import QlibxModel
from qlibx.onboarding import AgentTarget, OnboardingDesiredState, OnboardingRequest
from qlibx.portfolio import (
    ConstructionProfile,
    ExecutionLotInput,
    PortfolioConstructionRequest,
    PortfolioConstructionResult,
)
from qlibx.project import QlibxProject
from qlibx.specs.academic import AcademicRunSpec
from qlibx.specs.constraints import (
    ConstraintAdjustmentSpec,
    ConstraintMonitoringSpec,
    ConstraintValidationSpec,
    MvpConstraintPolicy,
)
from qlibx.specs.daily import (
    DailyAccountSeed,
    DailyMarketBinding,
    DailySimulationSpec,
    FrozenDailyExecutionSpec,
)
from qlibx.view import ModelView, StrategyView

__all__ = [
    "ACADEMIC_EXECUTION_CONTRACT",
    "STORED_SIGNAL_CONTRACT",
    "AcademicBatchRequest",
    "AcademicExchange",
    "AcademicExchangeProfile",
    "AcademicExecutionPreparation",
    "AcademicFill",
    "AcademicInstrumentKind",
    "AcademicInstrumentListing",
    "AcademicMatchResult",
    "AcademicPortfolioSnapshot",
    "AcademicPortfolioState",
    "AcademicPositionState",
    "AcademicPriceSemantics",
    "AcademicQuote",
    "AcademicRunSpec",
    "AcademicTargetWeight",
    "AgentTarget",
    "AnalysisResult",
    "ArtifactSemanticConstraint",
    "AvailableAtField",
    "BaseExchange",
    "BudgetMode",
    "CalendarLookback",
    "ComponentRequirement",
    "ConfirmedDelayRule",
    "ConstraintAdjustmentSpec",
    "ConstraintMonitoringSpec",
    "ConstraintValidationSpec",
    "ConstructionProfile",
    "CostRule",
    "DailyAccountSeed",
    "DailyMarketBinding",
    "DailySimulationSpec",
    "DatasetRegistration",
    "DatasetReindexResult",
    "DecisionAction",
    "EnsembleDefinition",
    "EnsembleMemberSpec",
    "EtfInstrument",
    "EveryCandidate",
    "EveryNSessions",
    "ExecutionLotInput",
    "ExecutionPreparation",
    "ForwardReturnLabelEntry",
    "ForwardReturnLabelModel",
    "ForwardReturnLabelResult",
    "FrozenDailyExecutionSpec",
    "KrxBatchRequest",
    "KrxExchange",
    "KrxExchangeConfig",
    "KrxExecutionPreparation",
    "MatchBatchResult",
    "ModelInvocation",
    "ModelOutputContract",
    "ModelView",
    "MonitoringAnalysisRequest",
    "MvpConstraintPolicy",
    "OnboardingDesiredState",
    "OnboardingRequest",
    "OperationError",
    "OperationOutcome",
    "OutcomeStatus",
    "PortfolioConstructionRequest",
    "PortfolioConstructionResult",
    "QlibxModel",
    "QlibxProject",
    "RegisteredStrategyExtension",
    "RendererKind",
    "ReportRequest",
    "ReportResult",
    "ResearchModel",
    "RowsLookback",
    "Side",
    "SignalAnalysisRequest",
    "SimulationAnalysisRequest",
    "SourceFormat",
    "StockInstrument",
    "StoredSignalEntry",
    "StoredSignalResult",
    "StoredSignalWeighting",
    "StrategyArtifactBinding",
    "StrategyArtifactModelRegistration",
    "StrategyArtifactModelSpec",
    "StrategyArtifactRequirement",
    "StrategyDraft",
    "StrategyExtensionRegistration",
    "StrategyExtensionSpec",
    "StrategyExtensionValidationRequest",
    "StrategyExtensionValidationResult",
    "StrategyInvocation",
    "StrategyResult",
    "StrategySourceStateLineage",
    "StrategyView",
    "TriggerContext",
    "TriggerDecision",
    "TriggerPolicy",
    "WeightEntry",
    "main",
]


def main() -> None:
    """Run the package CLI."""
    from qlibx.cli import main as cli_main

    cli_main()
