"""Generate a minimal ``entry.py`` component file.

Produces a stub that:
- Imports the echolon BaseComponent + EntrySignalOutput schema.
- Declares the ``entry_rule`` class expected by ``strategy/loader.py``.
- Returns HOLD for every bar — the coding agent fills in business logic.

Deliberately no pre-wired pathways, regime switches, or example indicator
reads. A scaffold that makes design decisions for the agent constrains the
design space; keep it empty so the agent owns the logic.
"""
from __future__ import annotations

from pathlib import Path

_TEMPLATE = '''"""Entry component — scaffold generated by echolon.strategy.generators.

TODO (coding agent):
  - Replace HOLD with your entry pathway logic.
  - Read indicators via ``self.get_indicator('<name>')``.
  - Read parameters via ``self.<param_name>`` (declared in strategy_params.py).
  - Return an EntrySignalOutput with signal, strength, type, entry_reason, intent, regime.
"""
from echolon.strategy.component import BaseComponent
from echolon.strategy.schemas import EntrySignalOutput


class entry_rule(BaseComponent):
    """Entry signal generator.

    The class name ``entry_rule`` is load-bearing: echolon/strategy/loader.py
    imports this exact symbol from entry.py. Do not rename.
    """

    def generate_signal(self) -> EntrySignalOutput:
        # TODO: design and implement entry pathway(s) per the strategy spec.
        return EntrySignalOutput(
            signal="HOLD",
            strength=0.0,
            type="hold",
            entry_reason="scaffold default — no pathway wired",
            intent=None,
            # Optional: TRS strategies populate regime with self.get_market_regime()
            # (interday) or self.get_session_phase() (intraday). TSMOM and other
            # paradigms typically leave regime unset.
            # regime=self.get_market_regime(),
        )
'''


def generate_entry(strategy_dir: Path | str, *, force: bool = False) -> Path:
    """Write ``entry.py`` into ``strategy_dir`` and return the path.

    Args:
        strategy_dir: Directory where entry.py will be written.
        force: If False (default), raise FileExistsError if the target file exists.
               If True, overwrite the target file.

    Returns:
        Path to the generated entry.py file.

    Raises:
        FileExistsError: if the target file exists and ``force`` is False.
    """
    strategy_dir = Path(strategy_dir)
    strategy_dir.mkdir(parents=True, exist_ok=True)
    out = strategy_dir / "entry.py"
    if out.exists() and not force:
        raise FileExistsError(
            f"{out} already exists — pass force=True to overwrite"
        )
    out.write_text(_TEMPLATE, encoding="utf-8")
    return out
