"""Generate a minimal ``exit.py`` component file.

Produces a stub that:
- Imports the echolon BaseComponent + ExitSignalOutput schema.
- Declares the ``exit_rule`` class expected by ``strategy/loader.py``.
- Returns no exit for every bar — the coding agent fills in business logic.

Deliberately no pre-wired stop levels, regime switches, or example indicator
reads. A scaffold that makes design decisions for the agent constrains the
design space; keep it empty so the agent owns the logic.
"""
from __future__ import annotations

from pathlib import Path

_TEMPLATE = '''"""Exit component — scaffold generated by echolon.strategy.generators.

TODO (coding agent):
  - Replace no_exit with your exit pathway logic.
  - Read indicators via ``self.get_indicator('<name>')``.
  - Read parameters via ``self.<param_name>`` (declared in strategy_params.py).
  - Return an ExitSignalOutput with should_exit, exit_reason, position_size, bars_since_entry, intent.
"""
from echolon.strategy.component import BaseComponent
from echolon.strategy.schemas import ExitSignalOutput


class exit_rule(BaseComponent):
    """Exit signal generator.

    The class name ``exit_rule`` is load-bearing: echolon/strategy/loader.py
    imports this exact symbol from exit.py. Do not rename.
    """

    def should_exit(self) -> ExitSignalOutput:
        # TODO: design and implement exit pathway(s) per the strategy spec.
        return ExitSignalOutput(
            should_exit=False,
            exit_reason="scaffold default — no exit logic",
            position_size=0.0,
            bars_since_entry=0,
            intent=None,
        )
'''


def generate_exit(strategy_dir: Path | str, *, force: bool = False) -> Path:
    """Write ``exit.py`` into ``strategy_dir`` and return the path.

    Args:
        strategy_dir: Directory where exit.py will be written.
        force: If False (default), raise FileExistsError if the target file exists.
               If True, overwrite the target file.

    Returns:
        Path to the generated exit.py file.

    Raises:
        FileExistsError: if the target file exists and ``force`` is False.
    """
    strategy_dir = Path(strategy_dir)
    strategy_dir.mkdir(parents=True, exist_ok=True)
    out = strategy_dir / "exit.py"
    if out.exists() and not force:
        raise FileExistsError(
            f"{out} already exists — pass force=True to overwrite"
        )
    out.write_text(_TEMPLATE, encoding="utf-8")
    return out
