"""Generate a minimal ``risk.py`` component file.

Produces a stub that:
- Imports the echolon BaseComponent + RiskOutput schema.
- Declares the ``risk_manager`` class expected by ``strategy/loader.py``.
- Returns trading allowed for every bar — the coding agent fills in business logic.

Deliberately no pre-wired risk checks, drawdown limits, or example indicator
reads. A scaffold that makes design decisions for the agent constrains the
design space; keep it empty so the agent owns the logic.
"""
from __future__ import annotations

from pathlib import Path

_TEMPLATE = '''"""Risk management component — scaffold generated by echolon.strategy.generators.

TODO (coding agent):
  - Replace trading_allowed with your risk check logic.
  - Read indicators via ``self.get_indicator('<name>')``.
  - Read parameters via ``self.<param_name>`` (declared in strategy_params.py).
  - Return a RiskOutput with trading_allowed and risk_reason.
"""
from echolon.strategy.component import BaseComponent
from echolon.strategy.schemas import RiskOutput


class risk_manager(BaseComponent):
    """Risk management decision maker.

    The class name ``risk_manager`` is load-bearing: echolon/strategy/loader.py
    imports this exact symbol from risk.py. Do not rename.
    """

    def can_trade(self) -> RiskOutput:
        # TODO: design and implement risk checks (drawdown limits, loss limits, etc).
        return RiskOutput(
            trading_allowed=True,
            risk_reason="scaffold default — no risk checks",
        )
'''


def generate_risk(strategy_dir: Path | str, *, force: bool = False) -> Path:
    """Write ``risk.py`` into ``strategy_dir`` and return the path.

    Args:
        strategy_dir: Directory where risk.py will be written.
        force: If False (default), raise FileExistsError if the target file exists.
               If True, overwrite the target file.

    Returns:
        Path to the generated risk.py file.

    Raises:
        FileExistsError: if the target file exists and ``force`` is False.
    """
    strategy_dir = Path(strategy_dir)
    strategy_dir.mkdir(parents=True, exist_ok=True)
    out = strategy_dir / "risk.py"
    if out.exists() and not force:
        raise FileExistsError(
            f"{out} already exists — pass force=True to overwrite"
        )
    out.write_text(_TEMPLATE, encoding="utf-8")
    return out
