"""Generate a minimal ``sizer.py`` component file.

Produces a stub that:
- Imports the echolon BaseComponent + EntrySignalOutput + SizerOutput schema.
- Declares the ``position_sizer`` class expected by ``strategy/loader.py``.
- Returns fixed 1-unit size for every entry signal — the coding agent fills in business logic.

Deliberately no pre-wired ATR multipliers, regime switches, or example indicator
reads. A scaffold that makes design decisions for the agent constrains the
design space; keep it empty so the agent owns the logic.
"""
from __future__ import annotations

from pathlib import Path

_TEMPLATE = '''"""Position sizer component — scaffold generated by echolon.strategy.generators.

TODO (coding agent):
  - Replace fixed 1-unit size with your sizing logic.
  - Read indicators via ``self.get_indicator('<name>')``.
  - Read parameters via ``self.<param_name>`` (declared in strategy_params.py).
  - Return a SizerOutput with calculated_size, signal_direction, sizing_reason, raw_size.
"""
from echolon.strategy.component import BaseComponent
from echolon.strategy.schemas import EntrySignalOutput, SizerOutput


class position_sizer(BaseComponent):
    """Position size calculator.

    The class name ``position_sizer`` is load-bearing: echolon/strategy/loader.py
    imports this exact symbol from sizer.py. Do not rename.
    """

    def calculate_size(self, entry_signal: EntrySignalOutput) -> SizerOutput:
        # TODO: design and implement sizing logic (ATR-based, equity-based, etc).
        return SizerOutput(
            calculated_size=1,
            signal_direction="HOLD",
            sizing_reason="scaffold default — fixed 1-unit size",
            raw_size=1.0,
        )
'''


def generate_sizer(strategy_dir: Path | str, *, force: bool = False) -> Path:
    """Write ``sizer.py`` into ``strategy_dir`` and return the path.

    Args:
        strategy_dir: Directory where sizer.py will be written.
        force: If False (default), raise FileExistsError if the target file exists.
               If True, overwrite the target file.

    Returns:
        Path to the generated sizer.py file.

    Raises:
        FileExistsError: if the target file exists and ``force`` is False.
    """
    strategy_dir = Path(strategy_dir)
    strategy_dir.mkdir(parents=True, exist_ok=True)
    out = strategy_dir / "sizer.py"
    if out.exists() and not force:
        raise FileExistsError(
            f"{out} already exists — pass force=True to overwrite"
        )
    out.write_text(_TEMPLATE, encoding="utf-8")
    return out
