"""Generate a minimal ``strategy.py`` coordinator file.

Produces a stub that:
- Imports the echolon BaseStrategy class.
- Declares the ``strategy_main`` class expected by ``strategy/loader.py``.
- Implements the canonical 4-step dispatch in ``_execute_bar``:
  1. Risk gate
  2. Exit check (if in position)
  3. Entry check (if flat)
  4. Sizer call

No pre-wired logic or decision gates. The scaffold makes the minimal
coordinator available; the coding agent refines with strategy-specific
gates, filters, or multi-signal coordination if needed.
"""
from __future__ import annotations

from pathlib import Path

_TEMPLATE = '''"""Strategy coordinator — scaffold generated by echolon.strategy.generators.

TODO (coding agent):
  - Refine _execute_bar with any pre-trade gates, filter logic, or
    multi-signal coordination your strategy requires.
  - The scaffold's body is the canonical minimal coordination flow:
    risk check → exit check (if in position) → entry check (if flat) → sizer.
"""
from echolon.strategy.base import BaseStrategy


class strategy_main(BaseStrategy):
    """Strategy coordinator — dispatches across entry / exit / risk / sizer.

    The class name ``strategy_main`` is load-bearing: echolon/strategy/loader.py
    imports this exact symbol via ``load_function("strategy", "strategy_main")``.
    Do not rename.
    """

    def _execute_bar(self) -> None:
        # TODO: add any strategy-specific gates or pre-trade logic.

        # 1. Risk gate
        risk_out = self.risk_manager.can_trade()
        if not risk_out.trading_allowed:
            return

        # 2. Exit-if-position
        if self.has_position() and not self.has_pending_orders():
            exit_out = self.exit_rule.should_exit()
            if exit_out.should_exit and exit_out.intent is not None:
                self.exit(exit_out.intent)
                return

        # 3. Entry-if-flat + sizer
        if not self.has_position() and not self.has_pending_orders():
            entry_out = self.entry_rule.generate_signal()
            if entry_out.signal != "HOLD" and entry_out.intent is not None:
                sizer_out = self.position_sizer.calculate_size(entry_out)
                if sizer_out.calculated_size > 0:
                    self.entry(entry_out.intent, sizer_out.calculated_size)
'''


def generate_strategy(strategy_dir: Path | str, *, force: bool = False) -> Path:
    """Write ``strategy.py`` into ``strategy_dir`` and return the path.

    Args:
        strategy_dir: Directory where strategy.py will be written.
        force: If False (default), raise FileExistsError if the target file exists.
               If True, overwrite the target file.

    Returns:
        Path to the generated strategy.py file.

    Raises:
        FileExistsError: if the target file exists and ``force`` is False.
    """
    strategy_dir = Path(strategy_dir)
    strategy_dir.mkdir(parents=True, exist_ok=True)
    out = strategy_dir / "strategy.py"
    if out.exists() and not force:
        raise FileExistsError(
            f"{out} already exists — pass force=True to overwrite"
        )
    out.write_text(_TEMPLATE, encoding="utf-8")
    return out
