"""
Parameter Architecture Framework

This module provides ONLY the architectural framework for parameter management.
It defines structure, types, and validation interfaces but NO specific parameters.

Specific parameters are defined in strategy_params.py based on the strategy
requirements from prompt.md files, generated by the parameter_agent.

Key Architectural Components:
- Parameter specification framework
- Component structure templates
- Parameter validation and coordination systems
- Optuna integration patterns

Note: Multi-agent composition interfaces have been removed in favor of
a streamlined workflow where parameter_agent generates complete parameter
definitions by reading all business logic prompts.
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, List, Tuple, Optional, Union, Callable
from dataclasses import dataclass
from enum import Enum
import optuna

from echolon.errors import raise_error


def validate_component_params(component_key: str, params: Dict[str, Any]) -> None:
    """Validate a single component's params sub-dict against framework contract.

    Currently enforces the ``printlog`` framework requirement. This helper is
    additive — it coexists with ``ComponentParameterTemplate.validate_structure``
    (which collects errors as a list) and raises a structured PRM-001 so an LLM
    agent gets a catalog error instead of an error-list return value.

    Parameters
    ----------
    component_key : str
        The params sub-dict key (``entry_params`` / ``exit_params`` /
        ``risk_params`` / ``sizer_params``).
    params : Dict[str, Any]
        The component's params sub-dict.

    Raises
    ------
    ParameterError
        PRM-001 if ``'printlog'`` is missing from ``params``.
    """
    if "printlog" not in params:
        raise_error(
            "PRM-001",
            file=__file__,
            function="validate_component_params",
            component_key=component_key,
        )


class ParameterType(Enum):
    """Framework for parameter data types."""
    INT = "int"
    FLOAT = "float"
    BOOL = "bool"
    CATEGORICAL = "categorical"
    FIXED = "fixed"


@dataclass
class ParameterSpec:
    """Framework specification for defining strategy parameters."""
    name: str
    param_type: ParameterType
    default_value: Any
    description: str = ""

    # Optimization bounds (for numeric types)
    min_value: Optional[Union[int, float]] = None
    max_value: Optional[Union[int, float]] = None
    step: Optional[Union[int, float]] = None

    # Categorical choices
    choices: Optional[List[Any]] = None

    # Validation functions (custom validation logic)
    validators: List[Callable[[Any], Tuple[bool, str]]] = None

    def __post_init__(self):
        """Initialize validation framework."""
        if self.validators is None:
            self.validators = []


class ComponentParameterTemplate(ABC):
    """
    Abstract framework for component parameter definition.

    Each component (Entry, Exit, Risk, Sizer) implements this to define
    their parameter structure according to strategy requirements.
    """

    @abstractmethod
    def get_component_name(self) -> str:
        """Return component identifier (e.g., 'entry', 'exit', 'risk', 'sizer')."""
        pass

    @abstractmethod
    def define_parameters(self) -> List[ParameterSpec]:
        """Define parameter specifications based on strategy requirements."""
        pass

    def get_default_structure(self) -> Dict[str, Any]:
        """Generate default parameter structure."""
        params = {'printlog': False}  # Standard framework requirement

        for spec in self.define_parameters():
            params[spec.name] = spec.default_value

        return params

    def generate_optuna_structure(self, trial: optuna.Trial, prefix: str = "") -> Dict[str, Any]:
        """Generate Optuna parameter structure."""
        params = {'printlog': False}  # Standard framework requirement
        component_prefix = f"{prefix}{self.get_component_name()}_" if prefix else f"{self.get_component_name()}_"

        for spec in self.define_parameters():
            param_name = f"{component_prefix}{spec.name}"

            if spec.param_type == ParameterType.INT:
                params[spec.name] = trial.suggest_int(param_name, spec.min_value, spec.max_value)
            elif spec.param_type == ParameterType.FLOAT:
                params[spec.name] = trial.suggest_float(
                    param_name, spec.min_value, spec.max_value, step=spec.step
                )
            elif spec.param_type == ParameterType.BOOL:
                params[spec.name] = trial.suggest_categorical(param_name, [True, False])
            elif spec.param_type == ParameterType.CATEGORICAL:
                params[spec.name] = trial.suggest_categorical(param_name, spec.choices)
            elif spec.param_type == ParameterType.FIXED:
                params[spec.name] = spec.default_value

        return params

    def validate_structure(self, params: Dict[str, Any]) -> Tuple[bool, List[str]]:
        """Validate parameter structure against framework requirements."""
        errors = []

        # Check required framework structure
        if 'printlog' not in params:
            errors.append("Missing required framework parameter: 'printlog'")

        # Validate defined parameters
        for spec in self.define_parameters():
            if spec.name not in params:
                errors.append(f"Missing required parameter: {spec.name}")
                continue

            value = params[spec.name]

            # Type validation framework
            if spec.param_type == ParameterType.INT and not isinstance(value, int):
                errors.append(f"Parameter '{spec.name}' must be integer, got {type(value)}")
            elif spec.param_type == ParameterType.FLOAT and not isinstance(value, (int, float)):
                errors.append(f"Parameter '{spec.name}' must be numeric, got {type(value)}")
            elif spec.param_type == ParameterType.BOOL and not isinstance(value, bool):
                errors.append(f"Parameter '{spec.name}' must be boolean, got {type(value)}")
            elif spec.param_type == ParameterType.CATEGORICAL and value not in spec.choices:
                errors.append(f"Parameter '{spec.name}' must be one of {spec.choices}, got {value}")

            # Range validation framework
            if spec.param_type in [ParameterType.INT, ParameterType.FLOAT]:
                if spec.min_value is not None and value < spec.min_value:
                    errors.append(f"Parameter '{spec.name}' must be >= {spec.min_value}, got {value}")
                if spec.max_value is not None and value > spec.max_value:
                    errors.append(f"Parameter '{spec.name}' must be <= {spec.max_value}, got {value}")

            # Custom validation framework
            for validator in spec.validators:
                is_valid, error_msg = validator(value)
                if not is_valid:
                    errors.append(f"Parameter '{spec.name}': {error_msg}")

        return len(errors) == 0, errors


class StrategyParameterFramework:
    """
    Multi-agent parameter composition framework.

    Provides the architectural pattern for composing parameters across
    components while maintaining coordination and consistency.
    """

    def __init__(self):
        self.component_templates: Dict[str, ComponentParameterTemplate] = {}
        self.coordination_rules: List[Dict[str, Any]] = []
        self.strategy_level_specs: List[ParameterSpec] = []

    def register_component(self, template: ComponentParameterTemplate):
        """Register component parameter template."""
        component_name = template.get_component_name()
        self.component_templates[component_name] = template

    def define_strategy_level_parameters(self, specs: List[ParameterSpec]):
        """Define strategy-level parameter specifications."""
        self.strategy_level_specs = specs

    def define_coordination_rule(self, rule_name: str, validation_func: Callable):
        """Define parameter coordination rule between components."""
        self.coordination_rules.append({
            'name': rule_name,
            'validator': validation_func
        })

    def compose_default_strategy(self) -> Dict[str, Any]:
        """Compose complete default strategy parameter structure."""
        strategy_params = {}

        # Compose component parameters
        for component_name, template in self.component_templates.items():
            strategy_params[f"{component_name}_params"] = template.get_default_structure()

        # Add strategy-level parameters
        for spec in self.strategy_level_specs:
            strategy_params[spec.name] = spec.default_value

        return strategy_params

    def compose_optuna_strategy(self, trial: optuna.Trial) -> Dict[str, Any]:
        """Compose complete Optuna strategy parameter structure."""
        strategy_params = {}

        # Compose component parameters
        for component_name, template in self.component_templates.items():
            strategy_params[f"{component_name}_params"] = template.generate_optuna_structure(trial)

        # Add strategy-level parameters
        for spec in self.strategy_level_specs:
            param_name = f"strategy_{spec.name}"

            if spec.param_type == ParameterType.INT:
                strategy_params[spec.name] = trial.suggest_int(param_name, spec.min_value, spec.max_value)
            elif spec.param_type == ParameterType.FLOAT:
                strategy_params[spec.name] = trial.suggest_float(
                    param_name, spec.min_value, spec.max_value, step=spec.step
                )
            elif spec.param_type == ParameterType.BOOL:
                strategy_params[spec.name] = trial.suggest_categorical(param_name, [True, False])
            elif spec.param_type == ParameterType.CATEGORICAL:
                strategy_params[spec.name] = trial.suggest_categorical(param_name, spec.choices)
            elif spec.param_type == ParameterType.FIXED:
                strategy_params[spec.name] = spec.default_value

        return strategy_params

    def validate_strategy_structure(self, params: Dict[str, Any]) -> Tuple[bool, List[str]]:
        """Validate complete strategy parameter structure."""
        errors = []

        # Validate component structures
        for component_name, template in self.component_templates.items():
            component_key = f"{component_name}_params"

            if component_key not in params:
                errors.append(f"Missing component parameters: {component_key}")
                continue

            is_valid, component_errors = template.validate_structure(params[component_key])
            if not is_valid:
                errors.extend([f"{component_name}: {error}" for error in component_errors])

        # Validate strategy-level parameters
        for spec in self.strategy_level_specs:
            if spec.name not in params:
                errors.append(f"Missing strategy parameter: {spec.name}")

        # Apply coordination rules
        for rule in self.coordination_rules:
            try:
                is_valid, rule_errors = rule['validator'](params)
                if not is_valid:
                    errors.extend([f"Coordination rule '{rule['name']}': {error}" for error in rule_errors])
            except Exception as e:
                errors.append(f"Coordination rule '{rule['name']}' failed: {str(e)}")

        return len(errors) == 0, errors

    def get_param_classifications(self) -> Dict[str, Dict[str, Any]]:
        """Export parameter classifications for all registered components.

        Returns:
            Dict mapping param_name -> {status, default, min?, max?, component}
        """
        classifications = {}
        for comp_name, template in self.component_templates.items():
            for spec in template.define_parameters():
                entry = {
                    "status": spec.param_type.name,  # "FIXED", "FLOAT", "INT"
                    "default": spec.default_value,
                    "component": comp_name,
                }
                if spec.param_type in (ParameterType.FLOAT, ParameterType.INT):
                    entry["min"] = spec.min_value
                    entry["max"] = spec.max_value
                classifications[spec.name] = entry
        return classifications

    # Multi-agent composition methods removed - no longer needed with parameter_agent workflow


# Multi-agent composition functionality removed - parameters are now generated
# directly by the parameter_agent from prompt.md files