"""File-format readers for strategy directory artifacts.

``calculator_params.json`` is the paradigm-blind file format for
classifier hyperparameters. It supports any registered classifier
(rule-based market regime, HMM, GMM, Carry term-structure, etc.) under
one schema.

File format (``calculator_params.json``)::

    {
      "version": 1,
      "calculators": {
        "market_regime": {
          "fast_ma_period": 12,
          "slow_ma_period": 30,
          "adx_period": 10,
          ...
        }
      }
    }
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional


_CALCULATOR_PARAMS_FILENAME = "calculator_params.json"


def load_calculator_params(strategy_dir: Path | str) -> Dict[str, Dict[str, Any]]:
    """Read calculator_params.json from a strategy directory.

    Args:
        strategy_dir: Path to the strategy directory containing the params file.

    Returns:
        Dict mapping calculator_name → params dict. Empty dict if the file
        is missing.
    """
    strategy_dir = Path(strategy_dir)
    path = strategy_dir / _CALCULATOR_PARAMS_FILENAME

    if path.exists():
        data = json.loads(path.read_text())
        version = data.get("version")
        if version == 1:
            return data.get("calculators", {}) or {}
        raise ValueError(
            f"Unknown calculator_params.json version: {version!r} in {path}"
        )

    return {}


def save_calculator_params(
    strategy_dir: Path | str,
    calculator_params: Dict[str, Dict[str, Any]],
) -> Path:
    """Write calculator_params.json in the v1 schema.

    Args:
        strategy_dir: Path to the strategy directory.
        calculator_params: Dict mapping calculator_name → params dict.

    Returns:
        Path to the written file.
    """
    strategy_dir = Path(strategy_dir)
    strategy_dir.mkdir(parents=True, exist_ok=True)
    out = strategy_dir / _CALCULATOR_PARAMS_FILENAME
    payload = {"version": 1, "calculators": calculator_params}
    out.write_text(json.dumps(payload, indent=2))
    return out


def get_regime_params(strategy_dir: Path | str) -> Optional[Dict[str, Any]]:
    """Convenience: extract just the ``market_regime`` calculator params.

    Equivalent to ``load_calculator_params(strategy_dir).get("market_regime")``.
    Returns ``None`` if the strategy has no regime classifier configured.
    """
    return load_calculator_params(strategy_dir).get("market_regime")


# =============================================================================
# resolved_params.json — the RESOLVED effective parameter vector (v1)
# =============================================================================
# Companion to selected_robust_trial.json: the trial file carries FLAT optuna
# names whose historical strip-once mappers provably mangle prefixed canonical
# names. This artifact carries the optimizer's exact nested component dicts
# (produced by echolon._internal.param_resolution.resolve_via_replay) so
# consumers (live trading_slot, BacktestRunner.best_trial) can load the
# effective vector VERBATIM, with no name mapping anywhere.
#
# File format (``resolved_params.json``)::
#
#     {
#       "version": 1,
#       "resolver": "optuna_fixed_trial_replay",
#       "provenance": {
#         "trial_number": 28,
#         "trial_params_sha256": "<sha256 of the paired trial's flat params>",
#         "generated_by": "echolon TrialSelector",
#         "created_utc": "2026-06-11T...Z"
#       },
#       "components": {
#         "entry_params": {...}, "exit_params": {...},
#         "risk_params": {...}, "sizer_params": {...}
#       }
#     }
#
# The sha256 provenance is load-bearing: consumers verify it against the flat
# params they just loaded, so a STALE pair (trial JSON regenerated by an old
# wheel over a dir holding an older resolved_params.json) is detected and the
# consumer falls back to the legacy mapping instead of running wrong values.

import hashlib
from dataclasses import dataclass

_RESOLVED_PARAMS_FILENAME = "resolved_params.json"


@dataclass(frozen=True)
class ResolvedParams:
    """Parsed resolved_params.json (v1)."""

    version: int
    components: Dict[str, Dict[str, Any]]
    provenance: Dict[str, Any]


def _json_scalar(obj: Any) -> Any:
    """Canonicalize non-JSON scalars (numpy) for fingerprint stability."""
    if hasattr(obj, "item"):
        return obj.item()
    return str(obj)


def trial_params_fingerprint(flat_params: Dict[str, Any]) -> str:
    """Canonical sha256 over a flat trial-params dict.

    Stable across the exporter side (pandas/numpy scalars) and the consumer
    side (values re-read from selected_robust_trial.json): numpy scalars are
    converted via ``.item()`` before serialization, and key order is fixed.
    """
    blob = json.dumps(flat_params, sort_keys=True, default=_json_scalar)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


def load_resolved_params(strategy_dir: Path | str) -> Optional["ResolvedParams"]:
    """Read resolved_params.json from a strategy directory.

    Returns None when the file is missing (callers fall back to the legacy
    mapping — the artifact is strictly opt-in). Raises ValueError on an
    unknown schema version; callers that must never raise catch it.
    """
    strategy_dir = Path(strategy_dir)
    path = strategy_dir / _RESOLVED_PARAMS_FILENAME
    if not path.exists():
        return None
    data = json.loads(path.read_text())
    version = data.get("version")
    if version != 1:
        raise ValueError(f"Unknown resolved_params.json version: {version!r} in {path}")
    return ResolvedParams(
        version=1,
        components=data.get("components", {}) or {},
        provenance=data.get("provenance", {}) or {},
    )


def save_resolved_params(
    strategy_dir: Path | str,
    components: Dict[str, Dict[str, Any]],
    *,
    provenance: Dict[str, Any],
) -> Path:
    """Write resolved_params.json in the v1 schema.

    Args:
        strategy_dir: Strategy directory (same dir as selected_robust_trial.json).
        components: The resolved nested dicts ({entry_params, exit_params, ...}).
        provenance: Must include trial_number + trial_params_sha256 of the
            paired trial file (see trial_params_fingerprint).

    Returns:
        Path to the written file.
    """
    strategy_dir = Path(strategy_dir)
    strategy_dir.mkdir(parents=True, exist_ok=True)
    out = strategy_dir / _RESOLVED_PARAMS_FILENAME
    payload = {
        "version": 1,
        "resolver": "optuna_fixed_trial_replay",
        "provenance": provenance,
        "components": components,
    }
    out.write_text(json.dumps(payload, indent=2, default=_json_scalar))
    return out
